"""Open every link that leaves the book in a new tab.

MyST has ``myst_links_external_new_tab``, but it only reaches links that MyST itself
parsed. The bibliography is generated by ``sphinxcontrib-bibtex`` straight into the
doctree, so its DOI and arXiv links would keep navigating away from the lesson you are
reading. A post-transform runs after everything has been resolved, which catches the
prose links, the reference lists and the bibliography in one place.

A link counts as external when it has a network location that is not the site's own.
Internal cross-references, anchors and ``mailto:`` have no netloc, so they are untouched.
"""

from __future__ import annotations

from urllib.parse import urlparse

from docutils import nodes
from sphinx.transforms.post_transforms import SphinxPostTransform


class ExternalLinksInNewTab(SphinxPostTransform):
    """Add ``target="_blank"`` (and a safe ``rel``) to off-site references."""

    default_priority = 500
    formats = ("html",)

    def run(self, **kwargs) -> None:
        own = urlparse(self.app.config.html_baseurl or "").netloc

        for node in self.document.findall(nodes.reference):
            netloc = urlparse(node.get("refuri", "")).netloc
            if not netloc or netloc == own:
                continue
            node["target"] = "_blank"
            # noopener denies the new tab access to window.opener; noreferrer also keeps
            # the referrer out of the request.
            node["rel"] = "noopener noreferrer"


def setup(app):
    app.add_post_transform(ExternalLinksInNewTab)
    return {
        "version": "1.0",
        "parallel_read_safe": True,
        "parallel_write_safe": True,
    }