"""Simplified NequIP (Batzner et al., Nat. Commun. 13, 2453, 2022) for the e3nn course.

Auto-generated by notebooks/08b_nequip_implementation.ipynb: do not edit by hand;
re-run that notebook to regenerate. Consumed by Lesson 08c (training) and
Lesson 11 (molecular dynamics with ASE).
"""

import torch
from torch import nn
from e3nn import o3
from e3nn.nn import FullyConnectedNet, Gate

def gate_for(irreps_out: o3.Irreps) -> Gate:
    """SiLU-based gate producing `irreps_out` (even scalars --> SiLU; odd
    scalars --> tanh)."""
    
    # Separate the output irreps into scalars (l=0) and gated irreps (l>0)
    irreps_scalars = o3.Irreps([(m, ir) for m, ir in irreps_out if ir.l == 0])
    irreps_gated = o3.Irreps([(m, ir) for m, ir in irreps_out if ir.l > 0])
    irreps_gates = o3.Irreps([(m, "0e") for m, _ in irreps_gated])
    
    # Define the activation functions for even and odd scalars
    act = {1: torch.nn.functional.silu, -1: torch.tanh}
    
    # Create and return a Gate instance with the specified irreps and activation
    # functions
    return Gate(irreps_scalars, [act[ir.p] for _, ir in irreps_scalars],
                irreps_gates, [torch.nn.functional.silu for _ in irreps_gates], irreps_gated)


def weighted_tp(irreps_in: o3.Irreps, irreps_sh: o3.Irreps, irreps_query: o3.Irreps):
    """'uvu' tensor product feature (x) filter with one path per allowed
    (l_i,l_f) --> l_o; per-edge weights come from MLP (shared_weights=False)."""
    
    # Compute the tensor product instructions and intermediate irreps based on the
    # input irreps, spherical harmonics irreps, and query irreps
    instructions, irreps_mid = [], []
    for i_1, (mul, ir_in) in enumerate(irreps_in):
        for i_2, (_, ir_sh) in enumerate(irreps_sh):
            # |l1-l2| <= l_o <= l1+l2;
            # p_o = p1 p2
            for ir_o in ir_in * ir_sh:
                if ir_o in irreps_query:
                    instructions.append((i_1, i_2, len(irreps_mid), "uvu", True))
                    irreps_mid.append((mul, ir_o))
    
    # Sort the intermediate irreps and update the instructions accordingly
    irreps_mid = o3.Irreps(irreps_mid)
    irreps_mid, permut, _ = irreps_mid.sort()
    instructions = [(i_1, i_2, permut[k], mode, train)
                    for i_1, i_2, k, mode, train in instructions]
    
    # Create and return a TensorProduct instance with the specified irreps and instructions
    return o3.TensorProduct(irreps_in, irreps_sh, irreps_mid, instructions,
                            shared_weights=False, internal_weights=False)


class BesselBasis(nn.Module):
    """Radial Bessel basis with polynomial cutoff envelope"""

    def __init__(self, r_cut: float, n_basis: int = 8, p: int = 6):
        super().__init__()
        # Store the cutoff radius, number of basis functions, and polynomial degree
        self.r_cut, self.n_basis, self.p = r_cut, n_basis, p
        
        # Trainable Bessel roots x pi, initialized at b = 1, ..., N_b
        self.b_pi = nn.Parameter(torch.pi * torch.arange(1, n_basis + 1).to(torch.float32))

    def envelope(self, x: torch.Tensor) -> torch.Tensor:
        # Compute the polynomial envelope function f_env(x) for x = r / r_cut
        p = self.p
        env = (1 - (p + 1) * (p + 2) / 2 * x**p + p * (p + 2) * x ** (p + 1)
               - p * (p + 1) / 2 * x ** (p + 2))
        
        # Zero (smoothly) beyond the cutoff
        return env * (x < 1.0)

    def forward(self, r: torch.Tensor) -> torch.Tensor:
        # Compute the Bessel basis functions for distances r
        x = r / self.r_cut
        bessel = (2.0 / self.r_cut) * torch.sin(self.b_pi * x[:, None]) / r[:, None]
        
        # Multiply by the polynomial envelope and return the result
        return bessel * self.envelope(x)[:, None]


class InteractionBlock(nn.Module):
    """One NequIP interaction block: conv + self-interactions + ResNet skip +
    gate."""

    def __init__(self, irreps_in, irreps_sh, irreps_out, n_basis=8, radial_neurons=64,
                 avg_num_neighbors=10.0):
        super().__init__()
        # Convert the input and spherical harmonics irreps to e3nn Irreps objects
        irreps_in, irreps_sh = o3.Irreps(irreps_in), o3.Irreps(irreps_sh)
        
        # Store the average number of neighbors for normalization in the forward pass
        self.avg_num_neighbors = avg_num_neighbors
        
        # Create a gate for the output irreps, which will be used to apply non-linearities
        self.gate = gate_for(o3.Irreps(irreps_out))
        
        # Define the linear layer for self-interaction (pre-processing)
        self.lin_pre = o3.Linear(irreps_in, irreps_in)
        
        # Define the weighted tensor product for the interaction block, which
        # combines the input features with the spherical harmonics features
        self.tp = weighted_tp(irreps_in, irreps_sh, self.gate.irreps_in)
        
        # Define the radial MLP that generates per-edge weights for the tensor product
        # 3 hidden layers, SiLU
        self.radial_mlp = FullyConnectedNet(
            [n_basis, radial_neurons, radial_neurons, radial_neurons, self.tp.weight_numel],
            torch.nn.functional.silu)
        
        # Define the linear layer for post-processing after the tensor product
        # and aggregation
        self.lin_post = o3.Linear(self.tp.irreps_out.simplify(), self.gate.irreps_in)
        
        # Define the skip connection for the ResNet-style skip connection, which
        # allows the input features to bypass the interaction block and be added to the output
        self.sc = o3.Linear(irreps_in, self.gate.irreps_in)
        
        # Store the output irreps for reference
        self.irreps_out = self.gate.irreps_out

    def forward(self, h, edge_index, edge_sh, edge_basis):
        # messages flow j -> i
        recv, send = edge_index
        
        # Apply the pre-processing linear layer to the input features
        x = self.lin_pre(h)
        
        # Compute the messages using the weighted tensor product, where the
        # weights are generated by the radial MLP based on the edge basis
        msg = self.tp(x[send], edge_sh, weight=self.radial_mlp(edge_basis))
        
        # Aggregate the messages by summing them for each receiving node and normalize
        agg = torch.zeros(h.shape[0], msg.shape[1], dtype=h.dtype, device=h.device)
        
        # sum_j / sqrt(N)
        agg = agg.index_add_(0, recv, msg) / self.avg_num_neighbors**0.5
        
        # x^{k+1} = f(x^k) + SI(x^k)
        return self.gate(self.lin_post(agg) + self.sc(h))


class SimpleNequIP(nn.Module):
    """Simplified NequIP; The species enter via a one-hot embedding."""

    def __init__(self, r_cut=6.0, n_species=1, n_basis=8, l_max=2, n_layers=3,
                 mul0=16, mul1=8, mul2=4, radial_neurons=64, avg_num_neighbors=10.0):
        super().__init__()
        
        # Store the hyperparameters in a dictionary for reference
        self.hparams = dict(r_cut=r_cut, n_species=n_species, n_basis=n_basis, l_max=l_max,
                            n_layers=n_layers, mul0=mul0, mul1=mul1, mul2=mul2,
                            radial_neurons=radial_neurons, avg_num_neighbors=avg_num_neighbors)
        
        # Store the cutoff radius and number of species for reference
        self.r_cut, self.n_species = r_cut, n_species
        
        # Filter Y up to l_max
        self.irreps_sh = o3.Irreps.spherical_harmonics(l_max)
        
        # B(r)
        self.basis = BesselBasis(r_cut, n_basis)
        
        # Define the hidden irreps for the interaction blocks based on the
        # specified multiplicities and maximum angular momentum
        irreps_hidden = o3.Irreps(f"{mul0}x0e + {mul0}x0o + {mul1}x1o + {mul1}x1e"
                                  + (f" + {mul2}x2e + {mul2}x2o" if l_max >= 2 else ""))
        
        # One-hot Z -> scalars
        self.embedding = o3.Linear(o3.Irreps(f"{n_species}x0e"),
                                   o3.Irreps(f"{mul0}x0e"))
        
        # Create a list of interaction blocks, each consisting of a convolution,
        # self-interaction, ResNet skip connection, and gate
        blocks, irreps = [], o3.Irreps(f"{mul0}x0e")
        for _ in range(n_layers):
            block = InteractionBlock(irreps, self.irreps_sh, irreps_hidden,
                                     n_basis, radial_neurons, avg_num_neighbors)
            blocks.append(block)
            irreps = block.irreps_out
        self.blocks = nn.ModuleList(blocks)
        self.out1 = o3.Linear(irreps, o3.Irreps("16x0e"))           # output block: l=0 features
        self.out2 = o3.Linear(o3.Irreps("16x0e"), o3.Irreps("1x0e"))
        
        # Define trainable parameters for energy scaling and shifting, which are
        # used to adjust the predicted energies
        self.energy_scale = nn.Parameter(torch.tensor(1.0))
        self.energy_shift = nn.Parameter(torch.tensor(0.0))

    def forward(self, pos, edge_index, species=None, batch=None):
        """pos (N,3), edge_index (2,E) [receiver, sender], species (N,) int or None,
        batch (N,) graph id or None  -->  total energy per graph, shape (n_graphs,)."""
        
        # If the batch information is not provided, create a default batch
        # tensor with all zeros
        if batch is None:
            batch = torch.zeros(pos.shape[0], dtype=torch.long, device=pos.device)
        if species is None:
            # Single species: all ones
            one_hot = torch.ones(pos.shape[0], self.n_species, dtype=pos.dtype, device=pos.device)
        else:
            one_hot = torch.nn.functional.one_hot(species, self.n_species).to(pos.dtype)
            
        # Course convention: messages flow j -> i
        recv, send = edge_index
        
        # r_ij = r_j - r_i
        vec = pos[send] - pos[recv]
        
        # Compute the spherical harmonics and Bessel basis for the edge vectors
        # Y(\hat r_ij)
        edge_sh = o3.spherical_harmonics(self.irreps_sh, vec, normalize=True,
                                         normalization="component")
        # B(r_ij)
        edge_basis = self.basis(vec.norm(dim=-1))
        
        # Pass the one-hot encoded species through the embedding layer to obtain
        # initial node features
        h = self.embedding(one_hot)
        for block in self.blocks:
            h = block(h, edge_index, edge_sh, edge_basis)
        
        # Compute the per-atom energies using the output layers and apply the
        # energy scaling and shifting
        e_atom = self.energy_scale * self.out2(self.out1(h)).squeeze(-1) + self.energy_shift
        
        # Determine the number of graphs in the batch based on the maximum batch
        # index
        n_graphs = int(batch.max()) + 1
        
        # E_pot = sum_i E_i
        return torch.zeros(n_graphs, dtype=pos.dtype, device=pos.device).index_add_(0, batch, e_atom)


def energy_and_forces(model, pos, edge_index, species=None, batch=None):
    """E_pot per graph and F = -dE/dr via autograd."""
    
    # Set the requires_grad attribute of the position tensor to True, allowing
    # gradients to be computed with respect to it
    pos = pos.requires_grad_(True)
    
    # Compute the total energy for the given positions, edge indices, species,
    # and batch
    E = model(pos, edge_index, species=species, batch=batch)
    
    # Compute the forces as the negative gradient of the summed energy with
    # respect to the positions, enabling the creation of a computation graph for
    # backpropagation
    F = -torch.autograd.grad(E.sum(), pos, create_graph=model.training)[0]
    
    # Return the computed energies and forces
    return E, F
